### PR TITLE
[Fixes #4] Replace ListView with RecyclerView

### LINKED ISSUE #4: Replace list view with recycle view

### PR DESCRIPTION
**Pull request by amy6**
## Description

Changes have been made to replace ListView with RecyclerView as per issue #4.

* RecyclerView implements the ViewHolder design pattern. RecyclerView properties have been set to ensure optimizations.
* Implemented Butterknife to help reduce boilerplate code for view binding.
* Renamed classes as per naming conventions. Organized the code into packages.
* Additionally, I found a few issues in the item layout which have been fixed in this PR. Screenshots below:

**Overlapping textviews**

ezgif com-resize 12

**Missing margins at the end of description**

ezgif com-resize 11

The button text which directs to the GitRepo link has been modified to display for max a single line with an ellipsis at the end.

Here's a full list screenshot:

ezgif com-resize 13

Feel free to let me know in case of further changes after review!

### CODE REVIEW

**Review by mojito9542 — CHANGES_REQUESTED** [review]
All the modifications are awesome, except that I liked the previous "show repo" text. So please make the changes

**Comment by amy6** [comment]
@mojito9542 The requested changes to show the full repo link has been made.

**Comment by mojito9542** [comment]
I am saying not to show the full link and simply show the button as previous

**Comment by amy6** [comment]
@mojito9542 Yes, the link is still a `Button`. I did not change it to a `TextView`. The only change I had made was to trim the button's text to a single line if it extended beyond one line. You can verify the same from the XML layout code. Let me know if I'm missing something here.

**Comment by mojito9542** [comment]
Ok, my bad..there was some confusion

**Review by mojito9542 — APPROVED** [review]

**Pull request closed without merging**
